apiVersion: v1
kind: Service
metadata:
  name: airflow-{{ .Values.appName }}
spec:
  type: LoadBalancer
  selector:
    deploy: airflow-{{ .Values.appName }}-web
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.airflow.port }}