---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nfs-server
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      hostNetwork: true
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: /nfs-data
          volumeMounts:
            - name: nfs-data
              mountPath: /nfs-data
      volumes:
        - name: nfs-data
          hostPath:
            path: /data/nfs
            type: DirectoryOrCreate
