appName: main

webReplicas: 1

airflow:
  image: 0hyeon/airflow-custom
  imageTag: '2.11.8'
  imagePullPolicy: Always
  port: 8080

service:
  port: 8080

worker:
  image: 0hyeon/airflow-custom
  imageTag: '2.11.8'
  imagePullPolicy: IfNotPresent

config:
  executor: 'KubernetesExecutor'

postgresql:
  conn: postgresql://airflow:airflow@airflow-postgres:5432
  password: airflow
