deployMode: statefulset

image:
  repository: 0hyeon/kafka-worker
  tag: "0.1.1"
  pullPolicy: IfNotPresent

kafka:
  brokers: 34.28.227.135:9092
  topic: category-match-in
  groupId: category-match-group

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "4Gi"

nfs:
  pvc: nfs-pvc