{{- if eq .Values.deployMode "ksvc" }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: category-match-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "50"
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "concurrency"
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          args:
            - --topic_to_consume={{ .Values.kafka.topic }}
            - --brokers={{ .Values.kafka.brokers }}
            - --group_id={{ .Values.kafka.groupId }}
          resources:
            limits:
              cpu: '{{ .Values.resources.limits.cpu }}'
              memory: '{{ .Values.resources.limits.memory }}'
            requests:
              cpu: '{{ .Values.resources.requests.cpu }}'
              memory: '{{ .Values.resources.requests.memory }}'
{{- end }}
