apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: category-match-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: BROKERS
              value: {{ .Values.kafka.brokers }}
            - name: TOPIC_TO_CONSUME
              value: {{ .Values.kafka.topic }}
            - name: TOPIC_TO_PRODUCE
              value: category-match-out
          volumeMounts:
            - mountPath: /data
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.nfs.pvc }}
