apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper
  clusterIP: None  # Kafka 내부에서만 접근 가능

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP  # Kafka 내부에서만 접근 가능
