image:
  repository: 0hyeon/kafka-worker
  tag: '0.1.0'
  pullPolicy: IfNotPresent

kafka:
  brokers: kafka-service.kafka.svc.cluster.local:9092
  topic: category-match-in
  groupId: category-match-group

nfs:
  pvc: nfs-pvc
