apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
spec:
  selector:
    name: airflow-postgres
  ports:
    - name: airflow-postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow-postgres
spec:
  serviceName: airflow-postgres
  replicas: 1
  selector:
    matchLabels:
      deploy: airflow-postgres
  template:
    metadata:
      labels:
        name: airflow-postgres
        deploy: airflow-postgres
    spec:
      restartPolicy: Always
      containers:
        - name: postgres
          image: postgres:11-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: dbvol
              mountPath: /var/lib/postgresql/data/pgdata
              subPath: pgdata
          env:
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: POSTGRES_DB
              value: airflow
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: dbvol
          emptyDir: {}