apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-init-{{ .Values.appName }}
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: airflow-db-init
          image: "{{ .Values.airflow.image }}:{{ .Values.airflow.imageTag }}"
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://airflow:{{ .Values.postgresql.password }}@airflow-postgres:5432/airflow-{{ .Values.appName }}"
          command: ["/bin/bash","-c"]
          args:
            - |
              set -e
              # 대상 DB 응답 대기
              until psql -h airflow-postgres -p 5432 -U airflow -d "airflow-{{ .Values.appName }}" -c '\q' >/dev/null 2>&1; do
                echo "Waiting for target DB (airflow-{{ .Values.appName }})..."; sleep 3;
              done
              airflow db init || true
              airflow db upgrade
