apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-pg-create-BRANCH
  labels:
    app: airflow
    component: pg-create
    branch: BRANCH
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: airflow
        component: pg-create
        branch: BRANCH
    spec:
      restartPolicy: Never
      containers:
        - name: airflow-pg-create
          image: postgres:11-alpine
          env:
            - name: PGPASSWORD
              value: airflow
          command: ["/bin/sh","-lc"]
          args: |
            set -e
            # Postgres 기동 대기
            until pg_isready -h airflow-postgres -p 5432 -U airflow -d postgres; do
              echo "Waiting for Postgres..."; sleep 2;
            done
            # DB 없으면 생성
            psql -h airflow-postgres -U airflow -d postgres -tAc \
              "SELECT 1 FROM pg_database WHERE datname='airflow-BRANCH'" | grep -q 1 \
              || createdb -h airflow-postgres -p 5432 -U airflow "airflow-BRANCH"
