apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-pg-delete
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: airflow-pg-delete
          image: postgres:11-alpine
          command: ["dropdb"]
          args: ['-h', 'airflow-postgres', '-p', '5432', '-U', 'airflow', 'airflow-BRANCH']
          env:
            - name: PGPASSWORD
              value: airflow
      restartPolicy: Never